services:
  - type: web
    name: tsa-item-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false  # You'll need to set this manually in Render dashboard